services:
  - type: web
    name: smartcart-unified
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RAPIDAPI_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        value: real-time-amazon-data.p.rapidapi.com
      - key: FLIPKART_RAPIDAPI_HOST
        value: real-time-flipkart-data2.p.rapidapi.com
      - key: UNIFIED_PRODUCT_RAPIDAPI_HOST
        value: realtime-flipkart-amazon-myntra-ajio-croma-product-details.p.rapidapi.com
